import { getAgentModel } from '@/lib/ai'
import prisma from '@/lib/prisma'
import { generateObject } from 'ai'
import { startOfDay } from 'date-fns'
import { z } from 'zod'

export const maxDuration = 30

const scopeSchema = z.object({
  initiative: z.object({
    title: z.string(),
    description: z.string().optional(),
    ambiguityLevel: z.enum(['HIGH', 'MEDIUM', 'LOW']),
    keyUnknowns: z.array(z.string()),
  }),
  projects: z.array(z.object({
    title: z.string(),
    description: z.string().optional(),
    expectedImpact: z.string().optional(),
    isL6PromoMaterial: z.boolean(),
    tasks: z.array(z.object({
      title: z.string(),
      context: z.string().optional(),
      size: z.enum(['XS', 'S', 'M', 'L', 'XL']),
      impact: z.enum(['NEEDLE', 'BUCKET']),
    })),
  })),
})

export async function POST(req: Request) {
  try {
    const { brainDump, objectiveId } = await req.json()
    
    const latestPlan = await prisma.plan.findFirst({
      orderBy: { date: 'desc' }
    })
    const preferences = latestPlan?.preferences ? (latestPlan.preferences as any) : null

    const model = getAgentModel('scope-slicer', preferences)

    const result = await generateObject({
      model: model as any,
      schema: scopeSchema,
      prompt: `You are the "Scope Slicer" AI Agent. Your job is to take a raw, unstructured brain-dump from a Product Manager and convert it into a structured, execution-ready hierarchy aligned with Google's L6 (Senior PM) expectations.

The PM wants to avoid the "tactical trap". You must:
1. Identify the overarching Initiative and its level of ambiguity. List the key unknowns that must be derisked.
2. Break it down into discrete Projects. Flag if a project is likely "L6 Promo Material" (high strategic impact).
3. Break projects down into Tasks.
4. Size mapping (Cognitive Load): XS (<15m), S (30m), M (60m), L (120m), XL (240m+).
5. Impact mapping: 
   - NEEDLE: Strategic, high-leverage, or derisking work (moves projects forward).
   - BUCKET: Maintenance, KTLO, administrative, or "filling the gaps".

Raw input from PM:
"""
${brainDump}
"""
      `,
    })

    const data = result.object

    // Optional: Auto-insert into database if objectiveId is provided
    let createdInitiativeId = null
    if (objectiveId) {
      const newInitiative = await prisma.initiative.create({
        data: {
          title: data.initiative.title,
          description: data.initiative.description,
          objectiveId: objectiveId,
          ambiguityLevel: data.initiative.ambiguityLevel,
          keyUnknowns: data.initiative.keyUnknowns,
        }
      })
      createdInitiativeId = newInitiative.id

      for (const p of data.projects) {
        const newProject = await prisma.project.create({
          data: {
            title: p.title,
            description: p.description,
            initiativeId: newInitiative.id,
            expectedImpact: p.expectedImpact,
            isL6PromoMaterial: p.isL6PromoMaterial,
          }
        })

        for (const t of p.tasks) {
          await prisma.task.create({
            data: {
              title: t.title,
              context: t.context,
              projectId: newProject.id,
              size: t.size as any,
              impact: t.impact as any,
              status: 'BACKLOG',
              aiGenerated: true,
              aiReasoning: "Generated by Scope Slicer Agent",
            }
          })
        }
      }
    }

    return Response.json({ success: true, data, createdInitiativeId })

  } catch (error: any) {
    console.error('Scope Slicer Error:', error)
    return Response.json({ success: false, error: error.message }, { status: 500 })
  }
}
